// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: sf/cosmos/transform/v1/transform.proto

package pbtransform

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CombinedFilter struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	EventTypeFilters   []*EventTypeFilter     `protobuf:"bytes,1,rep,name=event_type_filters,json=eventTypeFilters,proto3" json:"event_type_filters,omitempty"`
	EventOriginFilters []*EventOriginFilter   `protobuf:"bytes,2,rep,name=event_origin_filters,json=eventOriginFilters,proto3" json:"event_origin_filters,omitempty"`
	MessageTypeFilters []*MessageTypeFilter   `protobuf:"bytes,3,rep,name=message_type_filters,json=messageTypeFilters,proto3" json:"message_type_filters,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CombinedFilter) Reset() {
	*x = CombinedFilter{}
	mi := &file_sf_cosmos_transform_v1_transform_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombinedFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombinedFilter) ProtoMessage() {}

func (x *CombinedFilter) ProtoReflect() protoreflect.Message {
	mi := &file_sf_cosmos_transform_v1_transform_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombinedFilter.ProtoReflect.Descriptor instead.
func (*CombinedFilter) Descriptor() ([]byte, []int) {
	return file_sf_cosmos_transform_v1_transform_proto_rawDescGZIP(), []int{0}
}

func (x *CombinedFilter) GetEventTypeFilters() []*EventTypeFilter {
	if x != nil {
		return x.EventTypeFilters
	}
	return nil
}

func (x *CombinedFilter) GetEventOriginFilters() []*EventOriginFilter {
	if x != nil {
		return x.EventOriginFilters
	}
	return nil
}

func (x *CombinedFilter) GetMessageTypeFilters() []*MessageTypeFilter {
	if x != nil {
		return x.MessageTypeFilters
	}
	return nil
}

type EventTypeFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventTypes    []string               `protobuf:"bytes,1,rep,name=event_types,json=eventTypes,proto3" json:"event_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventTypeFilter) Reset() {
	*x = EventTypeFilter{}
	mi := &file_sf_cosmos_transform_v1_transform_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventTypeFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventTypeFilter) ProtoMessage() {}

func (x *EventTypeFilter) ProtoReflect() protoreflect.Message {
	mi := &file_sf_cosmos_transform_v1_transform_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventTypeFilter.ProtoReflect.Descriptor instead.
func (*EventTypeFilter) Descriptor() ([]byte, []int) {
	return file_sf_cosmos_transform_v1_transform_proto_rawDescGZIP(), []int{1}
}

func (x *EventTypeFilter) GetEventTypes() []string {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

type EventOriginFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventOrigins  []string               `protobuf:"bytes,1,rep,name=event_origins,json=eventOrigins,proto3" json:"event_origins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventOriginFilter) Reset() {
	*x = EventOriginFilter{}
	mi := &file_sf_cosmos_transform_v1_transform_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventOriginFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventOriginFilter) ProtoMessage() {}

func (x *EventOriginFilter) ProtoReflect() protoreflect.Message {
	mi := &file_sf_cosmos_transform_v1_transform_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventOriginFilter.ProtoReflect.Descriptor instead.
func (*EventOriginFilter) Descriptor() ([]byte, []int) {
	return file_sf_cosmos_transform_v1_transform_proto_rawDescGZIP(), []int{2}
}

func (x *EventOriginFilter) GetEventOrigins() []string {
	if x != nil {
		return x.EventOrigins
	}
	return nil
}

type MessageTypeFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageTypes  []string               `protobuf:"bytes,1,rep,name=message_types,json=messageTypes,proto3" json:"message_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageTypeFilter) Reset() {
	*x = MessageTypeFilter{}
	mi := &file_sf_cosmos_transform_v1_transform_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageTypeFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageTypeFilter) ProtoMessage() {}

func (x *MessageTypeFilter) ProtoReflect() protoreflect.Message {
	mi := &file_sf_cosmos_transform_v1_transform_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageTypeFilter.ProtoReflect.Descriptor instead.
func (*MessageTypeFilter) Descriptor() ([]byte, []int) {
	return file_sf_cosmos_transform_v1_transform_proto_rawDescGZIP(), []int{3}
}

func (x *MessageTypeFilter) GetMessageTypes() []string {
	if x != nil {
		return x.MessageTypes
	}
	return nil
}

var File_sf_cosmos_transform_v1_transform_proto protoreflect.FileDescriptor

const file_sf_cosmos_transform_v1_transform_proto_rawDesc = "" +
	"\n" +
	"&sf/cosmos/transform/v1/transform.proto\x12\x16sf.cosmos.transform.v1\"\xa1\x02\n" +
	"\x0eCombinedFilter\x12U\n" +
	"\x12event_type_filters\x18\x01 \x03(\v2'.sf.cosmos.transform.v1.EventTypeFilterR\x10eventTypeFilters\x12[\n" +
	"\x14event_origin_filters\x18\x02 \x03(\v2).sf.cosmos.transform.v1.EventOriginFilterR\x12eventOriginFilters\x12[\n" +
	"\x14message_type_filters\x18\x03 \x03(\v2).sf.cosmos.transform.v1.MessageTypeFilterR\x12messageTypeFilters\"2\n" +
	"\x0fEventTypeFilter\x12\x1f\n" +
	"\vevent_types\x18\x01 \x03(\tR\n" +
	"eventTypes\"8\n" +
	"\x11EventOriginFilter\x12#\n" +
	"\revent_origins\x18\x01 \x03(\tR\feventOrigins\"8\n" +
	"\x11MessageTypeFilter\x12#\n" +
	"\rmessage_types\x18\x01 \x03(\tR\fmessageTypesBMZKgithub.com/graphprotocol/proto-cosmos/pb/sf/cosmos/transform/v1;pbtransformb\x06proto3"

var (
	file_sf_cosmos_transform_v1_transform_proto_rawDescOnce sync.Once
	file_sf_cosmos_transform_v1_transform_proto_rawDescData []byte
)

func file_sf_cosmos_transform_v1_transform_proto_rawDescGZIP() []byte {
	file_sf_cosmos_transform_v1_transform_proto_rawDescOnce.Do(func() {
		file_sf_cosmos_transform_v1_transform_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sf_cosmos_transform_v1_transform_proto_rawDesc), len(file_sf_cosmos_transform_v1_transform_proto_rawDesc)))
	})
	return file_sf_cosmos_transform_v1_transform_proto_rawDescData
}

var file_sf_cosmos_transform_v1_transform_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_sf_cosmos_transform_v1_transform_proto_goTypes = []any{
	(*CombinedFilter)(nil),    // 0: sf.cosmos.transform.v1.CombinedFilter
	(*EventTypeFilter)(nil),   // 1: sf.cosmos.transform.v1.EventTypeFilter
	(*EventOriginFilter)(nil), // 2: sf.cosmos.transform.v1.EventOriginFilter
	(*MessageTypeFilter)(nil), // 3: sf.cosmos.transform.v1.MessageTypeFilter
}
var file_sf_cosmos_transform_v1_transform_proto_depIdxs = []int32{
	1, // 0: sf.cosmos.transform.v1.CombinedFilter.event_type_filters:type_name -> sf.cosmos.transform.v1.EventTypeFilter
	2, // 1: sf.cosmos.transform.v1.CombinedFilter.event_origin_filters:type_name -> sf.cosmos.transform.v1.EventOriginFilter
	3, // 2: sf.cosmos.transform.v1.CombinedFilter.message_type_filters:type_name -> sf.cosmos.transform.v1.MessageTypeFilter
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_sf_cosmos_transform_v1_transform_proto_init() }
func file_sf_cosmos_transform_v1_transform_proto_init() {
	if File_sf_cosmos_transform_v1_transform_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sf_cosmos_transform_v1_transform_proto_rawDesc), len(file_sf_cosmos_transform_v1_transform_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sf_cosmos_transform_v1_transform_proto_goTypes,
		DependencyIndexes: file_sf_cosmos_transform_v1_transform_proto_depIdxs,
		MessageInfos:      file_sf_cosmos_transform_v1_transform_proto_msgTypes,
	}.Build()
	File_sf_cosmos_transform_v1_transform_proto = out.File
	file_sf_cosmos_transform_v1_transform_proto_goTypes = nil
	file_sf_cosmos_transform_v1_transform_proto_depIdxs = nil
}
